version: '1'
services:
  orchestration:
    build: 
      context: .
      dockerfile: ./dockerfile.mage
    ports:
      - 6789:6789
    # volumes:
    #   - ./mage-ai:/home/src
    env_file:
      - .env