apiVersion: apps/v1
kind: Deployment
metadata:
  name: mage-ai-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mage-ai
  template:
    metadata:
      name: mage-ai-pods
      labels:
        app: mage-ai
    spec:
      containers:
      - name: mage-ai
        image: 863868025110.dkr.ecr.ap-southeast-1.amazonaws.com/parames-mage:latest # mageai/mageai:0.9.68
        ports:
        - containerPort: 6789
        envFrom:
          - secretRef:
              name: secret-mage
        imagePullPolicy: Always
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mage-ai-service
spec:
  type: NodePort
  selector:
    app: mage-ai
  ports:
    - port: 6789
      targetPort: 6789